### ISSUE TITLE
Speech recognition not supported on windows 8.1

### ISSUE THREAD

**Issue by boeckhoff** [HassoPlattnerInstituteHCI/Quake-DP#12]
Im getting the following error on my machine (windows 8.1). Could be that speech is only supported for windows 10 ? In any case we should make sure that we list exactly what OS Versions are supported aswell as offer a mode where you can type in answers so that I can still test the game even if speech does not work.

`UnityException: Speech recognition is not supported on this machine.
UnityEngine.Windows.Speech.KeywordRecognizer..ctor (System.String[] keywords, UnityEngine.Windows.Speech.ConfidenceLevel minimumConfidence) (at C:/buildslave/unity/build/Runtime/Export/Windows/Speech.cs:221)
WindowsSpeechIn.StartListening (System.String[] commands) (at Assets/SpeechIOForUnity/Assets/Scripts/Speech Input Core Scripts/WindowsSpeechIn.cs:35)
SpeechIO.SpeechIn+<Listen>d__11.MoveNext () (at Assets/SpeechIOForUnity/Assets/Scripts/Speech Input Core Scripts/SpeechIn.cs:73)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
GameManager+<IntroduceLevel>d__18.MoveNext () (at Assets/Scripts/GameManager.cs:69)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
GameManager+<Introduction>d__17.MoveNext () (at Assets/Scripts/GameManager.cs:55)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <567df3e0919241ba98db88bec4c6696f>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:114)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:94)`

**Comment by JotaroS** [comment]
(while I'm surprised to hear that you are still with windows 8) yes I will add them to readme.md of SpeechIOForUnity
